# Generated by Django 5.1.6 on 2025-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('estado', models.CharField(choices=[('En uso', 'En uso'), ('Para prueba', 'Para prueba')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
